export const movies = [
  {
    id: 1,
    title: "avengers",
    plot: "saving the world from thanos.",
    price: "$12",
    rating: 0,
    stars: 0,
    fav: false,
    cart: false,
    src: "https://rukminim2.flixcart.com/image/850/1000/l05lx8w0/poster/3/g/1/medium-amazing-spiderman-movie-d-on-fine-art-paper-hd-quality-original-imagcycz8ejdgkaq.jpeg?q=20&crop=false",
  },
  {
    id: 2,
    title: "ironman",
    plot: "wow iron man from thanos.",
    price: "$2",
    rating: 9,
    stars: 0,
    fav: false,
    cart: false,
    src: "https://rukminim2.flixcart.com/image/850/1000/l05lx8w0/poster/3/g/1/medium-amazing-spiderman-movie-d-on-fine-art-paper-hd-quality-original-imagcycz8ejdgkaq.jpeg?q=20&crop=false",
  },
  {
    id: 3,
    title: "spiderman haggu",
    plot: "saving the world from sand bag man.",
    price: "$32",
    rating: 4.9,
    stars: 3,
    fav: false,
    cart: false,
    src: "https://rukminim2.flixcart.com/image/850/1000/l05lx8w0/poster/3/g/1/medium-amazing-spiderman-movie-d-on-fine-art-paper-hd-quality-original-imagcycz8ejdgkaq.jpeg?q=20&crop=false",
  },
  {
    id: 4,
    title: "Haggu",
    plot: "saving the world from Hulk.",
    price: "$26",
    rating: 9,
    stars: 3.5,
    fav: false,
    cart: false,
    src: "https://rukminim2.flixcart.com/image/850/1000/l05lx8w0/poster/3/g/1/medium-amazing-spiderman-movie-d-on-fine-art-paper-hd-quality-original-imagcycz8ejdgkaq.jpeg?q=20&crop=false",
  },
];
